### ISSUE TITLE
pyrasite-memory-viewer error 

### ISSUE THREAD

**Issue by hunter-eric** [lmacken/pyrasite-gui#11]
Environment: Mac virtualenv python2.6

pyrasite-memory-viewer 78158
Traceback (most recent call last):
  File "/Users/eric/softpack/virtualenv/python2/bin/pyrasite-memory-viewer", line 11, in <module>
    load_entry_point('pyrasite==2.0', 'console_scripts', 'pyrasite-memory-viewer')()
  File "/Users/eric/softpack/virtualenv/python2/lib/python2.7/site-packages/pyrasite/tools/memory_viewer.py", line 150, in main
    objects = loader.load(filename)
  File "/Users/eric/softpack/virtualenv/python2/lib/python2.7/site-packages/meliae/loader.py", line 529, in load
    source, cleanup = files.open_file(source)
  File "/Users/eric/softpack/virtualenv/python2/lib/python2.7/site-packages/meliae/files.py", line 32, in open_file
    source = open(filename, 'rb')
IOError: [Errno 2] No such file or directory: '/tmp/pyrasite-78158-objects.json'

Thanks for help

**Comment by naoko** [comment]
I am getting the same error on Ubuntu python 3.6 virtualenv
```
pyrasite-memory-viewer 16847
Traceback (most recent call last):
  File "/usr/local/bin/pyrasite-memory-viewer", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/pyrasite/tools/memory_viewer.py", line 150, in main
    objects = loader.load(filename)
  File "/usr/lib/python2.7/dist-packages/meliae/loader.py", line 529, in load
    source, cleanup = files.open_file(source)
  File "/usr/lib/python2.7/dist-packages/meliae/files.py", line 32, in open_file
    source = open(filename, 'rb')
IOError: [Errno 2] No such file or directory: '/tmp/pyrasite-16847-objects.json'
```
appreciate any advice. thank you.

**Comment by andrewhavck** [comment]
@naoko Running the following commands helped resolve this issue for me on Ubuntu

```
# Used by pyrasite to inject code into a running process
sudo apt-get install gdb
 
# Used to allow pyrasite to inspect the internals of a running process
sudo apt-get install python-dbg
 
# Make sure that gdb can find debugging symbols for the virtualenv python
sudo mkdir -p /usr/lib/debug/opt/edx
sudo ln -s /usr/lib/debug/{usr,opt/edx}/bin
 
# Enable ptrace
echo 0 | sudo tee /proc/sys/kernel/yama/ptrace_scope

pip install Cython
pip install pyrasite meliae urwid
```

[Source](https://openedx.atlassian.net/wiki/plugins/servlet/mobile?contentId=19661968#content/view/19661968)

**Comment by hellertang** [comment]
` pyrasite-memory-viewer 45669
Traceback (most recent call last):
  File "/usr/local/bin/pyrasite-memory-viewer", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/pyrasite/tools/memory_viewer.py", line 150, in main
    objects = loader.load(filename)
  File "/usr/local/lib/python2.7/site-packages/meliae/loader.py", line 529, in load
    source, cleanup = files.open_file(source)
  File "/usr/local/lib/python2.7/site-packages/meliae/files.py", line 32, in open_file
    source = open(filename, 'rb')
IOError: [Errno 2] No such file or directory: '/tmp/pyrasite-45669-objects.json'`
appreciate any advice. thank you.

**Comment by qq1018408006** [comment]
> @naoko Running the following commands helped resolve this issue for me on Ubuntu
> 
> ```
> # Used by pyrasite to inject code into a running process
> sudo apt-get install gdb
>  
> # Used to allow pyrasite to inspect the internals of a running process
> sudo apt-get install python-dbg
>  
> # Make sure that gdb can find debugging symbols for the virtualenv python
> sudo mkdir -p /usr/lib/debug/opt/edx
> sudo ln -s /usr/lib/debug/{usr,opt/edx}/bin
>  
> # Enable ptrace
> echo 0 | sudo tee /proc/sys/kernel/yama/ptrace_scope
> 
> pip install Cython
> pip install pyrasite meliae urwid
> ```
> 
> [Source](https://openedx.atlassian.net/wiki/plugins/servlet/mobile?contentId=19661968#content/view/19661968)

it didnt work for me on ubuntu 20.03, python 3.8. There still exists error 'no such file or directory '/tmp/pyrasite-3572-objects.json'
'
