### ISSUE TITLE
TypeError when clicking on a process

### ISSUE THREAD

**Issue by Tinche** [lmacken/pyrasite-gui#9]
Ubuntu 14.04, Python 2.7.

When selected a process in the list of processes:

<pre>
Traceback (most recent call last):
  File "/home/tin/pg/pyrasite-gui/local/lib/python2.7/site-packages/pyrasite_gui/gui.py", line 599, in selection_cb
    self.generate_description(title)
  File "/home/tin/pg/pyrasite-gui/local/lib/python2.7/site-packages/pyrasite_gui/gui.py", line 469, in generate_description
    """ % (self.proc.title, p.status, p.getcwd(), ' '.join(p.cmdline),
TypeError
</pre>

**Comment by TheBengineer** [comment]
I also have this problem.

**Comment by spaceone** [comment]
This is basically a duplicate of Issue #8.
Downgrading psutil to version 1 will help. Otherwise here is a patch for using with psutil2: https://github.com/lmacken/pyrasite-gui/compare/develop...spaceone:patch-1

**Comment by con-f-use** [comment]
Very similar on Ubuntu 18.04, right after starting:
```
/usr/local/lib/python2.7/dist-packages/pyrasite_gui/gui.py:43: PyGIWarning: Pango was imported without specifying a version first. Use gi.require_version('Pango', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository import GLib, GObject, Pango, Gtk, WebKit
/usr/local/lib/python2.7/dist-packages/pyrasite_gui/gui.py:43: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import GLib, GObject, Pango, Gtk, WebKit
/usr/local/lib/python2.7/dist-packages/pyrasite_gui/gui.py:43: PyGIWarning: WebKit was imported without specifying a version first. Use gi.require_version('WebKit', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import GLib, GObject, Pango, Gtk, WebKit

(pyrasite-gui:23788): Gtk-CRITICAL **: 18:01:56.732: gtk_box_pack: assertion '_gtk_widget_get_parent (child) == NULL' failed
```
then when clicking a process:
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pyrasite_gui/gui.py", line 599, in selection_cb
    self.generate_description(title)
  File "/usr/local/lib/python2.7/dist-packages/pyrasite_gui/gui.py", line 469, in generate_description
    """ % (self.proc.title, p.status, p.getcwd(), ' '.join(p.cmdline),
AttributeError: 'Process' object has no attribute 'getcwd'
```

**Comment by programmin1** [comment]
"get" is no longer in the method name anymore I see, and I made a PR with the file I was working on - https://github.com/lmacken/pyrasite-gui/pull/26

However it still hangs.
